# Copyright (c) 2017-2021 Takeshi Yonezu
# All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:

  node1:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-1
    restart: always
    ports:
      - "50051:50051"
      - "7001:7001"
      - "50508:50508"
    environment:
      - IROHA_CONF=iroha-blockstore-1.conf
      - IROHA_NODEKEY=node1
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha1/block_store:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    depends_on:
      - postgres1

  node2:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-2
    restart: always
    environment:
      - IROHA_CONF=iroha-blockstore-2.conf
      - IROHA_NODEKEY=node2
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha2/block_store:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    depends_on:
      - postgres2

  node3:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-3
    restart: always
    environment:
      - IROHA_CONF=iroha-blockstore-3.conf
      - IROHA_NODEKEY=node3
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha3/block_store:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    depends_on:
      - postgres3

  node4:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-4
    restart: always
    environment:
      - IROHA_CONF=iroha-blockstore-4.conf
      - IROHA_NODEKEY=node4
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha4/block_store:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    depends_on:
      - postgres4

  postgres1:
    image: postgres:13-alpine
    container_name: iroha-postgres-1
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres2:
    image: postgres:13-alpine
    container_name: iroha-postgres-2
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres3:
    image: postgres:13-alpine
    container_name: iroha-postgres-3
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres4:
    image: postgres:13-alpine
    container_name: iroha-postgres-4
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

volumes:
  ccache-data:
