# Copyright (c) 2017-2021 Takeshi Yonezu
# All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:

  node21:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-21
    restart: always
    ports:
      - "50052:50051"
    environment:
      - IROHA_NODEKEY=node1
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha1/wsv:/tmp/wsv
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config

  node22:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-22
    restart: always
    environment:
      - IROHA_NODEKEY=node2
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha2/wsv:/tmp/wsv
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config

  node23:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-23
    restart: always
    environment:
      - IROHA_NODEKEY=node3
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha3/wsv:/tmp/wsv
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config

  node24:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-24
    restart: always
    environment:
      - IROHA_NODEKEY=node4
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha4/wsv:/tmp/wsv
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config

volumes:
  ccache-data:
