FROM arm32v7/iroha-pi-dev

ARG GITLOG="${GITLOG}"

LABEL GITLOG="${GITLOG}"

ENV IROHA_HOME=/opt/iroha
ENV LD_LIBRARY_PATH=${IROHA_HOME}/lib

COPY iroha ${IROHA_HOME}

RUN apt update && \
    apt upgrade -y && \
    useradd -ms /bin/bash iroha && \
    chown -R iroha:iroha ${IROHA_HOME}

WORKDIR ${IROHA_HOME}

CMD sleep 20; ${IROHA_HOME}/bin/irohad --config config/iroha.conf --genesis_block config/genesis.block --keypair_name config/node0
